gpu-operator:
  enabled: true
  operator:
    image: "mirror-gpu-operator"
    version: "v25.3.4"
    tolerations:
      - operator: "Exists"
    initContainer:
      enabled: false
  mig:
    strategy: mixed
  driver:
    enabled: false
  manager:
    enabled: false
  toolkit:
    image: "container-toolkit"
    version: "v1.13.1-centos7"
  devicePlugin:
    enabled: true
    image: "mirror-k8s-device-plugin"
    version: "v0.17.4"
  dcgm:
    enabled: false
  dcgmExporter:
    enabled: false
  gfd:
    image: "mirror-k8s-device-plugin"
    version: "v0.17.4"
  migManager:
    image: "k8s-mig-manager"
    version: "v0.12.3-ubuntu20.04"
    config:
      create: true
      name: "default-mig-config"
    env:
      - name: WITH_REBOOT
        value: "true"
  validator:
    image: "gpu-operator-validator"
    version: "v25.3.4"
  vgpuDeviceManager:
    enabled: false
  vfioManager:
    enabled: false
  sandboxDevicePlugin:
    enabled: false
  node-feature-discovery:
    master:
      tolerations:
        - operator: "Exists"
    worker:
      tolerations:
        - operator: "Exists"
    gc:
      tolerations:
        - operator: "Exists"
  daemonsets:
    tolerations:
      - operator: Exists
