# permissions for end users to edit sagemakerendpointregistrations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: AWSCrescendoInferenceOperator
  name: {{ .Values.namePrefix }}sagemakerendpointregistration-editor-role
  namespace: {{ .Values.namePrefix }}system
rules:
- apiGroups:
  - inference.sagemaker.aws.amazon.com
  resources:
  - sagemakerendpointregistrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inference.sagemaker.aws.amazon.com
  resources:
  - sagemakerendpointregistrations/status
  verbs:
  - get
