# permissions for end users to view sagemakerendpointregistrations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.namePrefix }}
  name: {{ .Values.namePrefix }}-sagemakerendpointregistration-viewer-role
  namespace: {{ .Values.shortPrefix }}-system
rules:
- apiGroups:
  - inference.sagemaker.aws.amazon.com
  resources:
  - sagemakerendpointregistrations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - inference.sagemaker.aws.amazon.com
  resources:
  - sagemakerendpointregistrations/status
  verbs:
  - get
