gpu-operator:
  gpu-operator:
    operator:
      repository: "248189928082.dkr.ecr.ap-northeast-1.amazonaws.com"
    toolkit:
      repository: "248189928082.dkr.ecr.ap-northeast-1.amazonaws.com/mirror-k8s"
    devicePlugin:
      repository: "248189928082.dkr.ecr.ap-northeast-1.amazonaws.com"
    gfd:
      repository: "248189928082.dkr.ecr.ap-northeast-1.amazonaws.com"
    migManager:
      repository: "248189928082.dkr.ecr.ap-northeast-1.amazonaws.com/mirror-cloud-native"
    validator:
      repository: "248189928082.dkr.ecr.ap-northeast-1.amazonaws.com/mirror-cloud-native"