gpu-operator:
  operator:
    repository: "034362067326.dkr.ecr.us-west-1.amazonaws.com"
  toolkit:
    repository: "034362067326.dkr.ecr.us-west-1.amazonaws.com/mirror-k8s"
  devicePlugin:
    repository: "034362067326.dkr.ecr.us-west-1.amazonaws.com"
  gfd:
    repository: "034362067326.dkr.ecr.us-west-1.amazonaws.com"
  migManager:
    repository: "034362067326.dkr.ecr.us-west-1.amazonaws.com/mirror-cloud-native"
  validator:
    repository: "034362067326.dkr.ecr.us-west-1.amazonaws.com/mirror-cloud-native"