gpu-operator:
  operator:
    repository: "741448945724.dkr.ecr.eu-west-1.amazonaws.com"
  toolkit:
    repository: "741448945724.dkr.ecr.eu-west-1.amazonaws.com/mirror-k8s"
  devicePlugin:
    repository: "741448945724.dkr.ecr.eu-west-1.amazonaws.com"
  gfd:
    repository: "741448945724.dkr.ecr.eu-west-1.amazonaws.com"
  migManager:
    repository: "741448945724.dkr.ecr.eu-west-1.amazonaws.com/mirror-cloud-native"
  validator:
    repository: "741448945724.dkr.ecr.eu-west-1.amazonaws.com/mirror-cloud-native"