apiVersion: inference.sagemaker.aws.amazon.com/v1alpha1
kind: ModelDeployment
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.namePrefix }}App
  name: modeldeployment-sample
spec:
  sageMakerEndpoint:
    name: sample-sagemaker-endpoint-phi-3
  model:
    modelHubName: SageMakerPublicHub
    modelId: huggingface-llm-phi-3-mini-4k-instruct
    modelVersion: 1.2.2
  server:
    instanceType: ml.g5.8xlarge
    maxAutoScaleReplicas: 2
    minAutoScaleReplicas: 1
    namespace: inference-namespace
  environmentVariables:
    - name: SAMPLE_ENV_VAR
      value: "sample_value"
  maxDeployTimeInSeconds: 1800
