apiVersion: inference.sagemaker.aws.amazon.com/v1alpha1
kind: ModelDeployment
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.namePrefix }}App
  name: modeldeployment-sample
spec:
  sageMakerEndpoint:
    name: sample-sagemaker-endpoint-t2t-flan
  model:
    acceptEula: true
    modelHubName: SageMakerPublicHub
    modelId: huggingface-text2text-flan-t5-xl
    modelVersion: 1.0.0
  server:
    instanceType: ml.g5.8xlarge
    maxAutoScaleReplicas: 2
    minAutoScaleReplicas: 1
    namespace: inference-namespace
  environmentVariables:
    - name: SAMPLE_ENV_VAR
      value: "sample_value"
  maxDeployTimeInSeconds: 1800
