apiVersion: inference.sagemaker.aws.amazon.com/v1
kind: JumpStartModel
metadata:
  labels:
    app.kubernetes.io/name: deepseek-llm-r1-distill-qwen-1-5b-app
  name: deepseek-sample
  namespace: ns-team-a
spec:
  sageMakerEndpoint:
    name: deepsek7bsme
  model:
    modelHubName: SageMakerPublicHub
    modelId: deepseek-llm-r1-distill-qwen-1-5b
    modelVersion: 2.0.4
  server:
    instanceType: ml.g5.8xlarge
    maxAutoScaleReplicas: 1
    minAutoScaleReplicas: 1
  environmentVariables:
    - name: SAMPLE_ENV_VAR
      value: "sample_value"
  maxDeployTimeInSeconds: 1800

