apiVersion: inference.sagemaker.aws.amazon.com/v1
kind: ModelDeployment
metadata:
  labels:
    app.kubernetes.io/name: huggingface-text2text-flan-t5-xl-app
  name: modeldeployment-sample
  namespace: ns-team-a
spec:
  sageMakerEndpoint:
    name: sample-sagemaker-endpoint
  model:
    acceptEula: true
    modelHubName: SageMakerPublicHub
    modelId: huggingface-text2text-flan-t5-xl
    modelVersion: 1.0.0
  server:
    instanceType: ml.g5.2xlarge
    maxAutoScaleReplicas: 2
    minAutoScaleReplicas: 1
    namespace: inference-namespace
  environmentVariables:
    - name: SAMPLE_ENV_VAR
      value: "sample_value"
  maxDeployTimeInSeconds: 1800
